language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: uk48W538qRyltuYv+0HsxUxKMneR4uYIWlT9lalZNNh8TIz9cDOIj132Lp7pYmN7SezLJ1LEPUM9+DqQpn3BYukA5dnQCpvILnzQAMLNV1qG8j690dAd0Bpq+R8SYWZcOUUKY+qQku/vsWnNVywvuVM0TNkYIO7mETMAev7HEHuIblk5IvoXhYc9xwVjbvR9o6sfh76V14xP0G5XxvBrQMLaXXDitNENTn8PkdoirpUjvz//oYocUhMgTArn6IvaDQ8igCTCfP0WMW6QFUYgf0q4rB2FyDEFikJ2ljFHZdrQy91YHCChLo9aZu5LdmcWN0EHFUHFaCWBiYCHarVDl4NGrODQEiBeO42F78l/iI3CPtbuqjmH9GjexghpxqilhjmXIFLPY3vb5CMjpJ0CFVuZ7FlS6GjS6FGEwghodDC+mHupVbpCer5fwCnOpSmY0KwhyU73F1OAotQaySIJRSU7jiCb1AqLig+D+/qx+nlQO6wOqbubgKicGp2Al2oDvsTp6c9T6zqCmCIAueBqP+tCmBVGZQ5kvzNUASd+quoxVJFKAg4Oj+cCkz7HkPmcl2pMuT5GvnukmDoRJHY4cj1kjDo0YMytoEIKVHafvKZ+tcuIUj56O59B+TNvjHpInFo8CRYskH0Bhy3ManWEuDin2+vAnyisLti/7EhVAWo=
  file: build/libs/xld-tomcat-provisioning-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: xebialabs-community/xld-tomcat-provisioning
notifications:
  hipchat:
    rooms:
      secure: xuBTdUsBzUwAmNUjh5dZBkQ6Dzo5RewIiiogqqmrPFlRoOw1doxABWhdbWwnD7iSW8RtCOIqOkG3sWXPGbrfSyKsD8xiW7SSTZ3zR6ZkQ1DZlHJa1LhRMxsGarWabTUTme/drqseTDMOX4X7EaDE0V08gbUl/4z+PF+kOKQIn0tyPFmd5XfdPXuyhKPj4UavXQUvcXmMwcD2BK8n3a61BwZR9t+6zxKi8ODtg7+O00JEbZ9LGYnYkGBTpBJxvLZ+sfTdqIYW1QeL8BpuU5V9pB5U8SbkNx87PU+HI45+vu5EN2EExxFhPP30fHBDHC+ZXCxmqScXEsTbWLr3kmd9Uj2Rry1ckN+pwuh9+lNGJqzLkR8pCl7UzNTUbyoGNaMlYv7KchojXiprsSdOCs5zt/19fQJiIwJ8pKFsILU22zcoNWCOqfM1p1+uc1+oeTkaSZTRfjwhN+tDdboexiIebxNIkkwNesYvo2i0fggh++Gu8IzD/xshD3hxjTxQT6/P8AWUJOoxQBr58YfWts2n39bFOBYOChfTY5lJngKFf9qg8seuJX889fjYxUJX7dQVqWgDx1F+3xMiLyMn1cLrWuTh/99vdc9WZIoiPAfDWOQRPCgj1FzoJURPDqwBoWP3LvcJE0lkrWGxEXcEMnh2HkAonhWqVVCMIod1Qh/YWbE=
